@host = https://localhost:7010
@tokenEndpoint = {{host}}/connect/token
@devClientId = dev-token-client
@email = admin@mail.local
@password = Geh1m_
@apiScope = banking_api

### 1) Dev-Login -> Access/ID/Refresh Token holen
POST {{tokenEndpoint}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=dev_password&client_id={{devClientId}}&email={{email}}&password={{password}}&scope=openid profile offline_access {{apiScope}}

> {%
   client.test("Status is 200", function() {
      client.assert(response.status === 200, "Expected HTTP 200");
   });

   client.test("Refresh token returned", function() {
      client.assert(!!response.body.refresh_token, "Missing refresh_token");
   });

   client.global.set("refreshToken", response.body.refresh_token);
   client.global.set("accessToken", response.body.access_token);
 %}

### 2) Refresh-Token verwenden
# Request 1 muss vorher erfolgreich gelaufen sein.
POST {{tokenEndpoint}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=refresh_token&client_id={{devClientId}}&refresh_token={{refreshToken}}

> {%
   client.test("Status is 200 on refresh", function() {
      client.assert(response.status === 200, "Expected HTTP 200");
   });

   client.test("Refreshed access token returned", function() {
      client.assert(!!response.body.access_token, "Missing refreshed access_token");
   });
 %}

